<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Breakdance.DotHttp" Version="8.*-*" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.*" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.*" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\CloudNimble.Supermemory\CloudNimble.Supermemory.csproj" />
    </ItemGroup>

</Project>
